openapi: 3.0.0

info:

  title: STD23054 - TD1
  version: 1.0.0

servers:

  - url: https://localhost.STD23054.com

paths:

  /customers:
    get:

      parameters:
        -in: querry
        name: Page
        schema:
          type: integer
        required : true
        description : Parametre obligatoire

        -in : query
        name : PageSize
        schema :
          type : 
        required : true
        description : Parametre obligatoire  

      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

components:

  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        id:
          type: string
